spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: apr14600
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
